
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author lenovo
 */
public class Admin extends javax.swing.JFrame {

    /**
     * Creates new form Admin
     */
    public Admin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        showadmindetails = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        admindetailstable = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        showadmindetails.setBackground(new java.awt.Color(153, 153, 255));
        showadmindetails.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        showadmindetails.setText("Show Data");
        showadmindetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showadmindetailsActionPerformed(evt);
            }
        });
        getContentPane().add(showadmindetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 170, 300, 50));

        admindetailstable.setAutoCreateRowSorter(true);
        admindetailstable.setBackground(new java.awt.Color(204, 204, 204));
        admindetailstable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 153)));
        admindetailstable.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        admindetailstable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "A_ID", "A_Name", "A_Mail", "A_Gender", "A_DOB", "A_address", "A_phoneNo"
            }
        ));
        admindetailstable.setGridColor(new java.awt.Color(102, 0, 102));
        admindetailstable.setSelectionBackground(new java.awt.Color(0, 204, 0));
        admindetailstable.setSelectionForeground(new java.awt.Color(0, 204, 0));
        jScrollPane1.setViewportView(admindetailstable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 1120, 400));

        jLabel3.setFont(new java.awt.Font("Algerian", 1, 48)); // NOI18N
        jLabel3.setText("        Admin");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 50, 380, 90));

        jButton1.setBackground(new java.awt.Color(153, 153, 153));
        jButton1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 20, 90, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon("E:\\3.1\\DB\\24_3_21\\ConnectMSSQL\\images\\a.jpg")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 50, 380, 90));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nevy3.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1120, 710));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void showadmindetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showadmindetailsActionPerformed
        // TODO add your handling code here:
        
        
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection connection = DriverManager.getConnection(
                    "jdbc:sqlserver://localhost:1433;databaseName=charity_management;selectMethod=cursor", "sa", "123456");

            System.out.println("DATABASE NAME IS:" + connection.getMetaData().getDatabaseProductName());

            Statement statement = connection.createStatement();
            ResultSet rs = statement
                    .executeQuery("SELECT * FROM AdminDetails");
            
            
            while (rs.next()) {
                String A_id=String.valueOf(rs.getInt("A_id"));
                String A_name=rs.getString("A_name");
                String A_mail=rs.getString("A_mail");

                String A_gender=rs.getString("A_gender");               
                String A_dob=rs.getString("A_DOB");
                String A_address=rs.getString("A_address");
                String A_phoneNo=rs.getString("A_phoneNo");
                
                
                                    
                        
                  String tbData[]={A_id,A_name,A_mail,A_gender,A_dob,A_address,A_phoneNo};
                   
                  DefaultTableModel tblModel=(DefaultTableModel)admindetailstable.getModel();
                  tblModel.addRow(tbData);
                 
            }
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    
    }//GEN-LAST:event_showadmindetailsActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         AdminTop A = new AdminTop();
                       A.show();
                       dispose(); //admin page a jbe

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable admindetailstable;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton showadmindetails;
    // End of variables declaration//GEN-END:variables
}
