
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author lenovo
 */
public class donationdetails extends javax.swing.JFrame {

    /**
     * Creates new form donationdetails
     */
    public donationdetails() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            java.sql.Connection connection = DriverManager.getConnection(
                "jdbc:sqlserver://localhost:1433;databaseName=charity_management;selectMethod=cursor", "sa", "123456");

            System.out.println("DATABASE NAME IS:" + connection.getMetaData().getDatabaseProductName());

            Statement statement = connection.createStatement();
            ResultSet rs = statement
            .executeQuery("SELECT * FROM records");

            while (rs.next()) {
                String d_id=String.valueOf(rs.getInt("d_id"));
                String n_id=String.valueOf(rs.getInt("n_id"));
                String p_id=String.valueOf(rs.getInt("p_id"));
                String sl=String.valueOf(rs.getInt("sl"));
                String q=String.valueOf(rs.getInt("quantity"));
               String u=rs.getString("unit");
             String n=rs.getString("productname");
                
                        
                String tbData[]={sl,d_id,n_id,p_id,n,q,u};

                DefaultTableModel tblModel=(DefaultTableModel)record.getModel();
                tblModel.addRow(tbData);

            }

        } catch (Exception e) {
            e.printStackTrace();
        } // TODO add your handling code here:
    }                                        

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:

       
        }           

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollP = new javax.swing.JScrollPane();
        DD = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        BACK = new javax.swing.JButton();
        showdonation = new javax.swing.JButton();
        Clear = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        DD.setBackground(new java.awt.Color(204, 204, 204));
        DD.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        DD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Donor Id", "Product Id", "Product Type", "Product Name", "Quantity", "Unit", "Date Of Donation"
            }
        ));
        jScrollP.setViewportView(DD);

        getContentPane().add(jScrollP, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 1090, 300));

        jLabel7.setFont(new java.awt.Font("Algerian", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("DONATION DETAILS");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, 480, 90));

        BACK.setBackground(new java.awt.Color(102, 102, 102));
        BACK.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        BACK.setForeground(new java.awt.Color(255, 255, 255));
        BACK.setText("Back");
        BACK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BACKActionPerformed(evt);
            }
        });
        getContentPane().add(BACK, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 40, -1, -1));

        showdonation.setBackground(new java.awt.Color(153, 153, 153));
        showdonation.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        showdonation.setText("Show All Data");
        showdonation.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 102), 3, true));
        showdonation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showdonationActionPerformed(evt);
            }
        });
        getContentPane().add(showdonation, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, 390, 50));

        Clear.setBackground(new java.awt.Color(153, 153, 153));
        Clear.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        Clear.setText("ClearTable");
        Clear.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearActionPerformed(evt);
            }
        });
        getContentPane().add(Clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 290, 120, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nevy3.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1090, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BACKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BACKActionPerformed
        // TODO add your handling code here:

        AdminTop d=new AdminTop();
        d.show();
        dispose();
    }//GEN-LAST:event_BACKActionPerformed

    private void showdonationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showdonationActionPerformed

        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            java.sql.Connection connection = DriverManager.getConnection(
                "jdbc:sqlserver://localhost:1433;databaseName=charity_management;selectMethod=cursor", "sa", "123456");

            System.out.println("DATABASE NAME IS:" + connection.getMetaData().getDatabaseProductName());

            Statement statement = connection.createStatement();
            ResultSet rs = statement
            .executeQuery("SELECT * FROM donationTable");

            while (rs.next()) {
                String SL=String.valueOf(rs.getInt("productid"));
                System.out.println(SL);
                String D_id=rs.getString("producttype");
                String N_id=rs.getString("productname");
                String P_id=String.valueOf(rs.getInt("quantity"));
                String q=rs.getString("dateofdonation");
                String pname=String.valueOf(rs.getInt("D_id"));
                String unit=rs.getString("unit");
               

                String tbData[]={pname,SL,D_id,N_id,P_id,unit,q};

                DefaultTableModel tblModel=(DefaultTableModel)DD.getModel();
                tblModel.addRow(tbData);

            }

        } catch (Exception e) {
            e.printStackTrace();
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_showdonationActionPerformed

    private void ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearActionPerformed

        // String tbData[]={p_id,p_type,p_name,p_quantity,pdate,D_id};
        DD.setModel(new DefaultTableModel(null,new String [] {"Donor Id","Product Id","Product Type","Product Name","Quantity","Unit","Date Of Donation"}));
        //tblModel.addRow(tbData);
        // TODO add your handling code here:
    }//GEN-LAST:event_ClearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(donationdetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(donationdetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(donationdetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(donationdetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new donationdetails().setVisible(true);
            }
        });
    }
    private javax.swing.JButton jButton2;
  //  private javax.swing.JButton BACK;
    private javax.swing.JLabel jLabel1;
 //   private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    //private javax.swing.JScrollPane jScrollP;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable record;
    private javax.swing.JTable showdonor;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BACK;
    private javax.swing.JButton Clear;
    private javax.swing.JTable DD;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollP;
    private javax.swing.JButton showdonation;
    // End of variables declaration//GEN-END:variables
}
