
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import javax.swing.JOptionPane;
import static javax.swing.text.html.HTML.Attribute.ID;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author lenovo
 */
public class donationTable extends javax.swing.JFrame {

    /**
     * Creates new form donationTable
     */
    public donationTable() {
        initComponents();
    }
    
    public donationTable(String id) {
        initComponents();
        ID.setText(id);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ID = new javax.swing.JTextField();
        p_name = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        p_type = new javax.swing.JComboBox<>();
        d_date = new javax.swing.JTextField();
        Donate_p = new javax.swing.JButton();
        Quantity = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        unit = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 115, -1));

        p_name.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(p_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 260, 240, 40));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Product Type:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 200, 100, -1));

        p_type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Electronics", "Food", "Furnitures", "Groceries", "Others" }));
        getContentPane().add(p_type, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 190, 230, 40));

        d_date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                d_dateActionPerformed(evt);
            }
        });
        getContentPane().add(d_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 450, 240, 40));

        Donate_p.setText("Donate");
        Donate_p.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Donate_pActionPerformed(evt);
            }
        });
        getContentPane().add(Donate_p, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 530, 170, 40));
        getContentPane().add(Quantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 320, 240, 40));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Date:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 460, 69, -1));

        jLabel13.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Id No.");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 270, 20));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Unit:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 380, 69, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Quantity");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 320, 69, -1));

        unit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unitActionPerformed(evt);
            }
        });
        getContentPane().add(unit, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 380, 240, 40));

        jButton5.setBackground(new java.awt.Color(102, 102, 102));
        jButton5.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Back");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 70, -1, -1));

        jLabel7.setFont(new java.awt.Font("Algerian", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("MAKE A DONATION");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, 480, 90));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Product Name:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 260, 120, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nevy3.jpg"))); // NOI18N
        jLabel3.setText("DateOfDonation");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, -20, 1100, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Donate_pActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Donate_pActionPerformed
        // TODO add your handling code here:   try {
            
    try{
        Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection connection = DriverManager.getConnection(
                    "jdbc:sqlserver://localhost:1433;databaseName=charity_management;selectMethod=cursor", "sa", "123456");

            System.out.println("DATABASE NAME IS:" + connection.getMetaData().getDatabaseProductName());

            Statement statement = connection.createStatement();
           
            
            
               String ptype= (String)p_type.getSelectedItem();
          
               String d_iD=ID.getText();
            
               String pname=p_name.getText();
               String qua=Quantity.getText();
               
               String ddate=d_date.getText();
               String u=unit.getText();
                           
                statement.executeUpdate("insert into donationTable (producttype,productname,quantity,dateofdonation,D_id,unit)"
                        + " values ('"+ptype+"','"+pname+"','"+qua+"','"+ddate+"','"+d_iD+"','"+u+"')");
                
                                     JOptionPane.showMessageDialog(null,"Donation Completed!");
               
    }                          
        
        

          catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_Donate_pActionPerformed

    private void unitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unitActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:

       // DonorTop d=new DonorTop();
      //  d.show();
      //  dispose();
      
           String x= ID.getText();
          DonorTop A = new DonorTop(x);
           A.setVisible(true);
           setVisible(false);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void d_dateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_d_dateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_d_dateActionPerformed
   /**
}     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(donationTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(donationTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(donationTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(donationTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new donationTable().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Donate_p;
    private javax.swing.JTextField ID;
    private javax.swing.JTextField Quantity;
    private javax.swing.JTextField d_date;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField p_name;
    private javax.swing.JComboBox<String> p_type;
    private javax.swing.JTextField unit;
    // End of variables declaration//GEN-END:variables
}
