/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author HP
 */
public class DonorTop extends javax.swing.JFrame {

    /**
     * Creates new form DonorTop
     */
    public DonorTop() {
        initComponents();
    }
   
    public DonorTop(String id) {
        initComponents();
        showId.setText(id);
    }    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        viewprofile = new javax.swing.JButton();
        Donate = new javax.swing.JButton();
        showId = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        r = new javax.swing.JButton();
        viewrecords1 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(102, 102, 102));
        jLabel3.setFont(new java.awt.Font("Algerian", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("DONOR HOME PAGE");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, 490, 70));

        viewprofile.setBackground(new java.awt.Color(102, 102, 102));
        viewprofile.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        viewprofile.setForeground(new java.awt.Color(255, 255, 255));
        viewprofile.setText("View Profile");
        viewprofile.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        viewprofile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewprofileActionPerformed(evt);
            }
        });
        getContentPane().add(viewprofile, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 360, 70));

        Donate.setBackground(new java.awt.Color(102, 102, 102));
        Donate.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        Donate.setForeground(new java.awt.Color(255, 255, 255));
        Donate.setText("Make a Donation");
        Donate.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Donate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DonateActionPerformed(evt);
            }
        });
        getContentPane().add(Donate, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, 360, 70));

        showId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showIdActionPerformed(evt);
            }
        });
        getContentPane().add(showId, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 130, 30));

        jLabel4.setBackground(new java.awt.Color(102, 102, 102));
        jLabel4.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("ID.No");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        jButton2.setBackground(new java.awt.Color(102, 102, 102));
        jButton2.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("View Seeker  Profile");
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 350, 360, 70));

        r.setBackground(new java.awt.Color(102, 102, 102));
        r.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        r.setForeground(new java.awt.Color(255, 255, 255));
        r.setText("View Needy Records");
        r.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        r.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rActionPerformed(evt);
            }
        });
        getContentPane().add(r, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 530, 360, 70));

        viewrecords1.setBackground(new java.awt.Color(102, 102, 102));
        viewrecords1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        viewrecords1.setForeground(new java.awt.Color(255, 255, 255));
        viewrecords1.setText("View My Records");
        viewrecords1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        viewrecords1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewrecords1ActionPerformed(evt);
            }
        });
        getContentPane().add(viewrecords1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 440, 360, 70));

        jButton1.setBackground(new java.awt.Color(102, 102, 102));
        jButton1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Log Out");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, -1));

        jLabel2.setBackground(new java.awt.Color(102, 102, 102));
        jLabel2.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nevy3.jpg"))); // NOI18N
        jLabel2.setText("ID.No");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void viewprofileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewprofileActionPerformed
        // TODO add your handling code here:
        
        
        
          String x= showId.getText();
          donorprofile A = new donorprofile(x);
                          A.setVisible(true);
                          setVisible(false);
    }//GEN-LAST:event_viewprofileActionPerformed

    private void DonateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DonateActionPerformed

        donationTable A = new donationTable(showId.getText());
        A.setVisible(true);
        setVisible(false);        // TODO add your handling code here:

    }//GEN-LAST:event_DonateActionPerformed

    
    private void showIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showIdActionPerformed
   
    }//GEN-LAST:event_showIdActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
      //  needyForDonor d=new needyForDonor();
      //  d.show();
     //   dispose();
         
          String x= showId.getText();
          needyForDonor A = new needyForDonor(x);
                          A.setVisible(true);
                          setVisible(false);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void rActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rActionPerformed
        // TODO add your handling code here:

      
      //    String x= showId.getText();
        String x= showId.getText();
          Records A = new Records(x);
                          A.setVisible(true);
                          setVisible(false);

    }//GEN-LAST:event_rActionPerformed

    private void viewrecords1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewrecords1ActionPerformed
        // TODO add your handling code here:
           String x= showId.getText();
          history A = new history(x);
                          A.setVisible(true);
                          setVisible(false);
        
    }//GEN-LAST:event_viewrecords1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        Login d=new Login();
        d.show();
        dispose();

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DonorTop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DonorTop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DonorTop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DonorTop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
    
       
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DonorTop().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Donate;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton r;
    private javax.swing.JTextField showId;
    private javax.swing.JButton viewprofile;
    private javax.swing.JButton viewrecords1;
    // End of variables declaration//GEN-END:variables
}
