
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 1a
 */
public class history extends javax.swing.JFrame {

    /**
     * Creates new form history
     */
    public history() {
        initComponents();
    }
    
      public history(String id) {
        initComponents();
        ID.setText(id);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        history = new javax.swing.JTable();
        showrecord = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        ID = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        Clear = new javax.swing.JButton();
        needy_donor = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        history.setBackground(new java.awt.Color(204, 204, 204));
        history.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        history.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "productid", "productname"
            }
        ));
        jScrollPane1.setViewportView(history);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 1080, 310));

        showrecord.setBackground(new java.awt.Color(153, 153, 153));
        showrecord.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        showrecord.setText("Show All Data");
        showrecord.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 102), 3, true));
        showrecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showrecordActionPerformed(evt);
            }
        });
        getContentPane().add(showrecord, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 150, 190, 50));

        jLabel13.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Id No.");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 70, 20));

        ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDActionPerformed(evt);
            }
        });
        getContentPane().add(ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 60, -1));

        jButton5.setBackground(new java.awt.Color(102, 102, 102));
        jButton5.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Back");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 50, -1, -1));

        jLabel3.setBackground(new java.awt.Color(102, 102, 102));
        jLabel3.setFont(new java.awt.Font("Algerian", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("My Donation Status");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, 570, 70));

        Clear.setBackground(new java.awt.Color(153, 153, 153));
        Clear.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        Clear.setText("ClearTable");
        Clear.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearActionPerformed(evt);
            }
        });
        getContentPane().add(Clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 280, 150, 40));

        needy_donor.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        needy_donor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "My_requested_and_taken_donations", "My_not_requested_or_not_taken_donations" }));
        needy_donor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        needy_donor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                needy_donorActionPerformed(evt);
            }
        });
        getContentPane().add(needy_donor, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 430, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nevy3.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void showrecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showrecordActionPerformed

        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            java.sql.Connection connection = DriverManager.getConnection(
                "jdbc:sqlserver://localhost:1433;databaseName=charity_management;selectMethod=cursor", "sa", "123456");

            System.out.println("DATABASE NAME IS:" + connection.getMetaData().getDatabaseProductName());
             String d_iD=ID.getText();
             
             

            Statement statement = connection.createStatement();
            
            
            
              {
                String value = (String) needy_donor.getSelectedItem();
                //  System.out.println(value);DONATIONS,SUCESSFUL_DONATIONS

                if (value.equals("My_requested_and_taken_donations")) {

                    try {
                      
           ResultSet rs = statement
            .executeQuery("(select p_id,productname  as pn from request where d_id='"+d_iD+"') union all (select p_id,r_productname as pn from records where d_id='"+d_iD+"')");

                        while (rs.next()) {
                            
                 String p_id=String.valueOf(rs.getInt("p_id"));
           //     String p_type=rs.getString("producttype");
                String p_name=rs.getString("pn");
                        
                  String tbData[]={p_id,p_name};
                   
                  DefaultTableModel tblModel=(DefaultTableModel)history.getModel();
                  tblModel.addRow(tbData);
                          

                        }
                    } catch (Exception e) {
                        e.printStackTrace();
                    }

                } else if (value.equals("My_not_requested_or_not_taken_donations")) {
                    try {

                        String sql = "Select productid,productname from donationtable where d_id='"+d_iD+"'and  productid not in((select p_id from request where d_id='"+d_iD+"') union all (select p_id from records where d_id='"+d_iD+"'))";

                        ResultSet rs = statement
                                .executeQuery(sql);
                        while (rs.next()) {
                              String p_id=String.valueOf(rs.getInt("productid"));
           //     String p_type=rs.getString("producttype");
                String p_name=rs.getString("productname");
                        
                  String tbData[]={p_id,p_name};
                   
                  DefaultTableModel tblModel=(DefaultTableModel)history.getModel();
                  tblModel.addRow(tbData);
                            
                            
                         
                        }
                    } catch (Exception e) {
                        e.printStackTrace();
                    }
                }
                
              
            }
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
   /*         ResultSet rs = statement
            .executeQuery("(select p_id,productname  as pn from request where d_id='"+d_iD+"') union all (select p_id,r_productname as pn from records where d_id='"+d_iD+"')");

            while (rs.next()) {
              String p_id=String.valueOf(rs.getInt("p_id"));
           //     String p_type=rs.getString("producttype");
                String p_name=rs.getString("pn");
                        
                  String tbData[]={p_id,p_name};
                   
                  DefaultTableModel tblModel=(DefaultTableModel)history.getModel();
                  tblModel.addRow(tbData);

            }*/

        } catch (Exception e) {
            e.printStackTrace();
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_showrecordActionPerformed

    private void IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:

        String x= ID.getText();
        DonorTop A = new DonorTop(x);
        A.setVisible(true);
        setVisible(false);

    }//GEN-LAST:event_jButton5ActionPerformed

    private void ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearActionPerformed

        // String tbData[]={p_id,p_type,p_name,p_quantity,pdate,D_id};
        history.setModel(new DefaultTableModel(null,new String [] {"productid","productname"}));
        //tblModel.addRow(tbData);
        // TODO add your handling code here:
    }//GEN-LAST:event_ClearActionPerformed

    private void needy_donorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_needy_donorActionPerformed
        // TODO add your handling code here:

        //String  s=
    }//GEN-LAST:event_needy_donorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(history.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(history.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(history.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(history.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new history().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Clear;
    private javax.swing.JTextField ID;
    private javax.swing.JTable history;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> needy_donor;
    private javax.swing.JButton showrecord;
    // End of variables declaration//GEN-END:variables
}
//My_requested_and_taken_donations,My_not_requested_or_not_taken_donations,