
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author HP
 */
public class Ratings extends javax.swing.JFrame {

    /**
     * Creates new form Ratings
     */
    public Ratings() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        showrating = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Ratingtable = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        toptable = new javax.swing.JTable();
        Showtopproducts = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Clear = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jInternalFrame1.setVisible(true);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Algerian", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("   Ratings");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, 210, 70));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 50, 430, 70));

        showrating.setBackground(new java.awt.Color(153, 153, 153));
        showrating.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        showrating.setText("Show Rating");
        showrating.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 102), 2));
        showrating.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showratingActionPerformed(evt);
            }
        });
        getContentPane().add(showrating, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 250, 140, 30));

        Ratingtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "D_id", "Rating"
            }
        ));
        jScrollPane1.setViewportView(Ratingtable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 540, 350));

        toptable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ProductName", "Quantity"
            }
        ));
        jScrollPane2.setViewportView(toptable);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 280, 520, 350));

        Showtopproducts.setBackground(new java.awt.Color(153, 153, 153));
        Showtopproducts.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        Showtopproducts.setText("Show Data");
        Showtopproducts.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 102), 2, true));
        Showtopproducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowtopproductsActionPerformed(evt);
            }
        });
        getContentPane().add(Showtopproducts, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 220, 120, 30));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 200, -1, 20));

        jButton5.setBackground(new java.awt.Color(102, 102, 102));
        jButton5.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Back");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 40, -1, -1));

        jLabel5.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Top three SUCessfully donted products");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 230, 510, 70));

        jLabel6.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("donor ratings");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 160, 70));

        Clear.setBackground(new java.awt.Color(153, 153, 153));
        Clear.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        Clear.setText("ClearTable");
        Clear.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearActionPerformed(evt);
            }
        });
        getContentPane().add(Clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 205, 120, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nevy3.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ShowtopproductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowtopproductsActionPerformed
        // TODO add your handling code here:
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            java.sql.Connection connection = DriverManager.getConnection(
                    "jdbc:sqlserver://localhost:1433;databaseName=charity_management;selectMethod=cursor", "sa", "123456");

            System.out.println("DATABASE NAME IS:" + connection.getMetaData().getDatabaseProductName());

            Statement statement = connection.createStatement();
            ResultSet rs = statement
                    .executeQuery("select Top 3 R_productname ,sum(R_Quantity) as quantity from records group by R_productname order by quantity desc");
            
            
            while (rs.next()) {
                String quantity=String.valueOf(rs.getInt("Quantity"));
                String productname=rs.getString("R_productname");
             
                        
                  String tbData[]={productname,quantity};
                   
                  DefaultTableModel tblModel=(DefaultTableModel)toptable.getModel();
                  tblModel.addRow(tbData);
                 
            }
            
            
            
            
            
            
            
            
            
            
            
            
            
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_ShowtopproductsActionPerformed

    private void showratingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showratingActionPerformed
        // TODO add your handling code here:
        
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            java.sql.Connection connection = DriverManager.getConnection(
                    "jdbc:sqlserver://localhost:1433;databaseName=charity_management;selectMethod=cursor", "sa", "123456");

            System.out.println("DATABASE NAME IS:" + connection.getMetaData().getDatabaseProductName());

            Statement statement1 = connection.createStatement();
            
             ResultSet rs1 = statement1
                    .executeQuery("select D_id,count(Distinct N_id) as totalneedy from records group by D_id");
             
                      while (rs1.next()) {
                String D=String.valueOf(rs1.getInt("D_id"));
                    // System.out.println(Did);
                String nid=String.valueOf(rs1.getInt("totalneedy"));
                
               Statement statement2 = connection.createStatement();
                statement2.executeUpdate("insert into noofneedy_per_donor (D_id,Noofneedy) values('"+D+"','"+nid+"')");
                
               }
            
                 
             
             
             
             
             
             
              Statement statement = connection.createStatement();
            ResultSet rs = statement
                    .executeQuery("select D_id,rating from noofneedy_per_donor n inner join ratings r on "
                            + "(n.Noofneedy between r.lowestsale and r.highestsale) ");
           
             
            
            
            
            while (rs.next()) {
                String D_id=String.valueOf(rs.getInt("D_id"));
                String r=rs.getString("rating");
               // String A_mail=rs.getString("N_id");

               // String A_gender=rs.getString("P_id");               
               // String A_dob=rs.getString("A_DOB");
               // String A_address=rs.getString("A_address");
               // String A_phoneNo=rs.getString("A_phoneNo");
                
                
                                    
                        
                  String tbData[]={D_id,r};
                   
                  DefaultTableModel tblModel=(DefaultTableModel)Ratingtable.getModel();
                  tblModel.addRow(tbData);
                 
            }
            
            
            
            
            
            
            
            
            
            
            
            
            
            
        } catch (Exception e) {
            e.printStackTrace();
        }
        
                        


        
        
    }//GEN-LAST:event_showratingActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:

        AdminTop d=new AdminTop();
        d.show();
        dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearActionPerformed

        // String tbData[]={p_id,p_type,p_name,p_quantity,pdate,D_id};
        Ratingtable.setModel(new DefaultTableModel(null,new String [] {"D_id","Rating"}));
        
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            java.sql.Connection connection = DriverManager.getConnection(
                    "jdbc:sqlserver://localhost:1433;databaseName=charity_management;selectMethod=cursor", "sa", "123456");

            System.out.println("DATABASE NAME IS:" + connection.getMetaData().getDatabaseProductName());

            Statement statement1 = connection.createStatement();
            
             ResultSet rs1 = statement1
                    .executeQuery("delete from noofneedy_per_donor");
             
                   
            
            
            
        } catch (Exception e) {
            System.out.println("Deleted Sucessfully");
        }
        //tblModel.addRow(tbData);
        // TODO add your handling code here:
    }//GEN-LAST:event_ClearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ratings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ratings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ratings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ratings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ratings().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Clear;
    private javax.swing.JTable Ratingtable;
    private javax.swing.JButton Showtopproducts;
    private javax.swing.JButton jButton5;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton showrating;
    private javax.swing.JTable toptable;
    // End of variables declaration//GEN-END:variables
}
